source 'https://rubygems.org'

gem 'aws-sdk-cloudwatch',     '~> 1.0'
gem 'aws-sdk-dynamodb',       '~> 1.0'
gem 'aws-sdk-s3',             '~> 1.0'
gem 'aws-sdk-secretsmanager', '~> 1.0'
gem 'dotenv',                 '~> 2.7', require: 'dotenv/load'
gem 'pry',                    '~> 0.13'
gem 'rake',                   '~> 13.0'
gem 'rspec',                  '~> 3.9', require: 'rspec/core/rake_task'
gem 'simplecov',              '~> 0.21'
gem 'twitter',                '~> 7.0'
gem 'yake',                   '~> 0.3'
