#!/usr/bin/env ruby
require "dotenv/load"

VERSION = %x(git describe --tags --always).strip

rum :"brutalismbot/brutalismbot" do
  tag VERSION

  env :AWS_ACCESS_KEY_ID
  env :AWS_DEFAULT_REGION
  env :AWS_SECRET_ACCESS_KEY
  env :RUNTIME                            => "ruby2.5"
  env :TF_VAR_release                     => tag
  env :TF_VAR_twitter_access_token        => ENV["TWITTER_ACCESS_TOKEN"]
  env :TF_VAR_twitter_access_token_secret => ENV["TWITTER_ACCESS_TOKEN_SECRET"]
  env :TF_VAR_twitter_consumer_key        => ENV["TWITTER_CONSUMER_KEY"]
  env :TF_VAR_twitter_consumer_secret     => ENV["TWITTER_CONSUMER_SECRET"]

  stage :build
  stage :test => :build
  stage :plan => :test

  artifact "lambda.zip" => :build

  desc "Publish lambda package"
  run :publish => :build do
    cmd %W[aws s3 cp lambda.zip s3://brutalismbot/pkg/lambda/brutalismbot-#{VERSION}.zip]
  end

  desc "Apply infrastructure"
  run :apply => :plan

  default ["lambda.zip", :plan]
end
