#!/usr/bin/env ruby
rum :"brutalismbot/brutalismbot" do

  tag %x(git describe --tags --always).strip

  env :AWS_ACCESS_KEY_ID
  env :AWS_SECRET_ACCESS_KEY
  env :AWS_DEFAULT_REGION
  env :RUNTIME => "ruby2.5"
  env :TF_VAR_release => tag

  stage :build
  stage :test => :build
  stage :plan => :test

  artifact "lambda.zip" => :build

  desc 'Apply infrastructure'
  run :apply => :plan

  default ["lambda.zip", :plan]
end
