require_relative 'lib/aws'
require_relative 'lib/reddit'

AGE        ||= ENV.fetch('MIN_AGE_HOURS', '4').to_i.hours
TABLE_NAME ||= ENV.fetch('TABLE_NAME', 'brutalismbot-blue')

METRICS     ||= Aws::CloudWatch::Metrics.new
STATE       ||= Aws::DynamoDB::State.new

Yake.logger.formatter = ->(_sev, time, _prog, msg) do
  "#{time.strftime('%Y-%m-%d %H:%M:%S')} - #{msg}\n"
end

file 'new.json' do
  sh %{open 'https://old.reddit.com/r/brutalism/new.json?raw_json=1'}
  $stderr.write 'press RETURN when contents copied to clipboard... '
  $stdin.gets
  sh %{pbpaste > new.json.tmp}
  sh %{jq . new.json.tmp > new.json}
  rm 'new.json.tmp'
end

task :build => 'new.json' do
  sh %{docker build --tag brutalismbot/reddit-pop .}
end

task :client => 'new.json' do
  @client = Reddit::Brutalism.new('new.json')
end

task :cursor do
  @cursor = STATE.cursor
end

task :pop => %i[cursor client] do
  queue = @client.latest @cursor
  post  = queue.shift if queue.first&.created_before?(UTC.now - AGE)

  @queue_size = queue.size
  @next_post  = post&.to_item
end

task :update_metrics => :pop do
  METRICS.update_queue_size @queue_size
end

task :default => :update_metrics do
  STATE.update @queue_size, @next_post
end
