source 'https://rubygems.org/'

gem 'yake', '~> 0.8'

group :development do
  gem 'aws-sdk-cloudwatch',  '~> 1.0'
  gem 'aws-sdk-eventbridge', '~> 1.0'
  gem 'aws-sdk-lambda',      '~> 1.0'
  gem 'aws-sdk-states',      '~> 1.0'
end
