name: blue
on:
  pull_request:
    paths:
      - blue/**
  push:
    paths:
      - blue/**
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/plan
        with:
          name: blue
          token: ${{ secrets.TF_API_TOKEN }}
