name: functions
on:
  pull_request:
    paths:
      - functions/**
  push:
    paths:
      - functions/**
jobs:
  plan-functions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/plan
        with:
          name: functions
          token: ${{ secrets.TF_API_TOKEN }}
        env:
          TF_VAR_MAIL_TO: ${{ secrets.TF_VAR_MAIL_TO }}
