name: global
on:
  pull_request:
    paths:
      - .github/**
      - global/**
  push:
    paths:
      - .github/**
      - global/**
jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/plan
        with:
          name: global
          token: ${{ secrets.TF_API_TOKEN }}
        env:
          TF_VAR_MAIL_TO: ${{ secrets.TF_VAR_MAIL_TO }}
