name: website
on:
  pull_request:
    paths:
      - website/**
  push:
    paths:
      - website/**
jobs:
  plan-website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/plan
        with:
          name: website
          token: ${{ secrets.TF_API_TOKEN }}
